---
defaults: &defaults
  working_directory: /kafka-connect-bigquery

version: 2
jobs:
  build_and_upload_artifact:
    <<: *defaults
    docker:
      - image: mycujoo/java-docker
    steps:
      - checkout
      - run:
          name: debug git
          command: |
            git status

      - run:
          name: Publish to artifactory
          command: |
            ./gradlew clean distTar artifactoryPublish

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_upload_artifact:
          context: org-data-platform
          filters:
            branches:
              only:
                - development
                - master
                - production
